### ISSUE TITLE
DPIR strength=0 still affects image

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-denoise#93]
There may be cases where the user wants to only perform DPIR on specific scenes using zoning, and otherwise leave the video untouched. Currently however, `strength=0` still changes the image quite substantially. `strength=None` also doesn't work (despite being given in the typehint), and it simply errors.

See: [comp](https://slow.pics/c/teAhoGDA)

**Comment by NSQY** [comment]
Looks like chroma is being resampled too. You can make this obvious by passing something like ``kernel=Lanczos(taps=10)``.

**Comment by Setsugennoao** [comment]
> Looks like chroma is being resampled too. You can make this obvious by passing something like `kernel=Lanczos(taps=10)`.

well ofc, it has to go through RGB

**Comment by Setsugennoao** [comment]
As for the strength, 0.0 is a valid input for the neural network, the issue should be moved to "None isn't accepted", which makes sense since the functions was thought as having a base strength, and the zones were an afterthought.
I think i'll be reworking this with zones like other functions.


So, like, `strength={None: 10, (100, 200): 50}` will be the same as doing `strength=10, ranges=[((100, 200), 50)]` now.

**Comment by LightArrowsEXE** [comment]
Fixed in f77afc11433bca135c329e21a18ec06c01f03303
